util/models.py
from .db import db


class Configuration(db.EmbeddedDocument):
    config_name = db.StringField(required=True)
    stock = db.BooleanField()


class Item(db.Document):
    name = db.StringField(required=True)
    manufacturer = db.StringField()
    price = db.FloatField()
    stock = db.BooleanField(required=True)
    url = db.URLField(required=True)
    lastStocked = db.DateTimeField()
    date_added = db.DateTimeField()
    img_url = db.URLField(required=True)
    config = db.EmbeddedDocumentListField(Configuration)
    meta = {'collection': 'items'}

    def __str__(self) -> str:
        if self.stock:
            stock_msg = "# **In stock**"
        else:
            stock_msg = '> Out of stock'
        return "{}\n[${}]({})\n{}\n < Last in stock: {} >\n".format(
            self.name, self.price, self.url, stock_msg, self.lastStocked)


class Change(db.Document):
    item_name = db.StringField(required=True)
    restock = db.BooleanField(required=True)
    timestamp = db.DateTimeField(required=True)
    meta = {'collection': 'changes'}


class Taskmeta(db.DynamicDocument):
    status = db.StringField()
    result = db.ListField()
    children = db.ListField()
    date_done = db.DateTimeField()
    meta = {'collection': 'taskmeta'}

app.py
from flask import Flask 
from util.db import initialize_db
from celeryfile.celeryinit import make_celery
from routes.webpages import webpages
from routes.items_api import items_api
from routes.staticpages import staticpages


app = Flask(__name__)
app.register_blueprint(webpages)
app.register_blueprint(items_api)
app.register_blueprint(staticpages)
app.config['MONGODB_SETTINGS'] = {
    'db': 'items',
    'host': 'localhost',
    'port': 27017,
    'connect': False
}

celery = make_celery(app)
celery.autodiscover_tasks(['celeryfile'])
initialize_db(app)


if __name__ == "__main__":
    app.run(debug=True)

routes/items_api.py
from flask import Blueprint, jsonify
from util.mongo_adaptor import MongoAdaptor
MongoAdaptor = MongoAdaptor()

items_api = Blueprint('items_api', __name__)

@items_api.route('/api/items/all', methods=['GET'])
def items():
    items = MongoAdaptor.fetch_items_dict()
    for item in items:
        del item['_id']     
    return jsonify(items)

@items_api.route('/api/changes/all', methods=['GET'])
def changes():
    items = MongoAdaptor.fetch_changes_dict()
    for item in items:
        del item['_id']     
    return jsonify(items)

routes/staticpages.py
from flask import Blueprint, render_template, request, url_for, redirect

staticpages = Blueprint('staticpages', __name__, template_folder='templates',static_folder='static')

@staticpages.route('/about')
def about():
    return render_template('about.html')

@staticpages.route('/faq')
def faq():
    return render_template('faq.html')

routes/webpages.py
from flask import Blueprint, render_template, request, url_for, redirect
from util.mongo_adaptor import MongoAdaptor
from datetime import datetime
MongoAdaptor = MongoAdaptor()

webpages = Blueprint('webpages', __name__, template_folder='templates',static_folder='static')


@webpages.route('/index')
@webpages.route('/')
def index():
    items = MongoAdaptor.fetch_items_dict(3)
    return render_template('index.html', title='Home', items=items)


@webpages.route('/search', methods=['GET', 'POST'])
def search():
    items = MongoAdaptor.fetch_items_dict()
    if request.method == 'POST':
        req = request.form
        print(req)
        query = req.get('search')
        query_result = parse_query(query, items)
        return render_template('search_results.html', items=query_result, query=query)
    return render_template('search.html')


def parse_query(query, items):
    queries = query.split()
    result = []
    for item in items:
        for q in queries:
            if q in item['name'].lower().split():
                result.append(item)
    return result


@webpages.route('/items')
def items():
    page = int(request.args.get('page', 1))
    limit = int(request.args.get('limit', 5))
    items = MongoAdaptor.paginate_items(page, limit)
    return render_template('items.html', number=10, paginated_items=items, page_num=page)


@webpages.route('/items/brand/<manufacturer>')
def manufacturer_items(manufacturer):
    page = int(request.args.get('page', 1))
    limit = int(request.args.get('limit', 8))
    brand_items = MongoAdaptor.paginate_items(
        page, limit, manufacturer)
    return render_template('brand_items.html', number=5, paginated_items=brand_items, page_num=page, title=manufacturer)


@webpages.route('/dashboard')
def dashboard():
    recent_changes = MongoAdaptor.fetch_changes_dict(3)
    items = MongoAdaptor.fetch_items_dict()
    in_stock = [item for item in items if item['stock']]
    last_update = MongoAdaptor.fetch_taskresults_dict(1)
    date = last_update[0]['date_done']
    date = datetime(int(date[:4]), int(date[5:7]), int(
        date[8:10]), int(date[11:13]), int(date[14:16]))
    time_formatted = date.strftime(r"%A, %b %d %I:%M%p")
    return render_template('dashboard.html', date=time_formatted, changes=recent_changes, items=in_stock)

templates/_item.html
  <div
    class="row g-1 border rounded overflow-hidden flex-md-row mb-3 shadow-sm h-md-250 position-relative"
  >
    <div class="col p-4 d-flex flex-column position-relative">
      <strong class="d-inline-block mb-2 text-primary"
        >{{ item.manufacturer}}</strong
      >
      <h5 class="mb-1">{{ item.name }}</h5>
      <div class="mb-auto text-muted">{% if item.price %} ${{ item.price }} {% endif %}</div>
      <p class="card-text mb-auto">
        {% if item.stock %}<a style="color:green"> In stock</a>{% else %} <a style="color:crimson">Out of stock</a>
        {% endif %}
      </p>
    </div>
    <div class="col-auto d-none d-lg-block">
      <a href = {{ item.url }}>
      <img src={{ item.img_url }} alt="..." width= auto height="150">
      </a>
    </div>
  </div>

templates/about.html
{% extends "base.html" %} {% block app_content %}
<div class="row mb-2">
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Rogue</strong>
          <h3 class="mb-auto">Ohio Deadlift Bar </h3>
          <div class="mb-1 text-muted">$550</div>
          <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img class="img-thumbnail" src=https://assets.roguefitness.com/f_auto,q_auto,h_763,b_rgb:f8f8f8/catalog/Weightlifting%20Bars%20and%20Plates/Barbells/Mens%2020KG%20Barbells/AU-RA0963-BLBR/AU-RA0963-BLBR-h_t4opya.png width="200" height="250" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">Design</strong>
          <h3 class="mb-0">Post title</h3>
          <div class="mb-1 text-muted">Nov 11</div>
          <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
          <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

        </div>
      </div>
    </div>
  </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <!-- <link href={{ url_for('webpages.static', filename = 'blog.css') }} rel="stylesheet"> -->
    <title>
      {% block title %} {% if title %} {{ title }} - Stockbot {% else %} Welcome
      to Stockbot {% endif %} {% endblock %}
    </title>
  </head>
  <body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand" href="{{ url_for('webpages.index') }}" style="color: whitesmoke;">  Stockbot</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href='{{ url_for('webpages.index') }}' style="color: azure;">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('staticpages.about') }}" style="color: azure;">About</a>
            </li>
          </ul>
          <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
            <li class="nav-item col-6 col-md-auto">
              <a class="nav-link p-2" href="https://github.com/bingx1/" target="_blank" rel="noopener">
                <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" class="navbar-nav-svg d-inline-block align-text-top" viewBox="0 0 512 499.36" role="img"><title>GitHub</title><path fill="currentColor" fill-rule="evenodd" d="M256 0C114.64 0 0 114.61 0 256c0 113.09 73.34 209 175.08 242.9 12.8 2.35 17.47-5.56 17.47-12.34 0-6.08-.22-22.18-.35-43.54-71.2 15.49-86.2-34.34-86.2-34.34-11.64-29.57-28.42-37.45-28.42-37.45-23.27-15.84 1.73-15.55 1.73-15.55 25.69 1.81 39.21 26.38 39.21 26.38 22.84 39.12 59.92 27.82 74.5 21.27 2.33-16.54 8.94-27.82 16.25-34.22-56.84-6.43-116.6-28.43-116.6-126.49 0-27.95 10-50.8 26.35-68.69-2.63-6.48-11.42-32.5 2.51-67.75 0 0 21.49-6.88 70.4 26.24a242.65 242.65 0 0 1 128.18 0c48.87-33.13 70.33-26.24 70.33-26.24 14 35.25 5.18 61.27 2.55 67.75 16.41 17.9 26.31 40.75 26.31 68.69 0 98.35-59.85 120-116.88 126.32 9.19 7.9 17.38 23.53 17.38 47.41 0 34.22-.31 61.83-.31 70.23 0 6.85 4.61 14.81 17.6 12.31C438.72 464.97 512 369.08 512 256.02 512 114.62 397.37 0 256 0z"></path></svg>
                <small class="d-md-none ms-2">GitHub</small>
              </a>
            </li>
            <li class="nav-item col-6 col-md-auto">
              <a class="nav-link p-2" href="https://discord.com/channels/811885227290263572/811885227290263575" target="_blank" rel="noopener">
                <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" class="navbar-nav-svg d-inline-block align-text-top" viewBox="0 0 24 24" role="img"><title>Discord</title><path fill="currentColor" fill-rule="evenodd" d="M20.222 0c1.406 0 2.54 1.137 2.607 2.475V24l-2.677-2.273l-1.47-1.338l-1.604-1.398l.67 2.205H3.71c-1.402 0-2.54-1.065-2.54-2.476V2.48C1.17 1.142 2.31.003 3.715.003h16.5L20.222 0zm-6.118 5.683h-.03l-.202.2c2.073.6 3.076 1.537 3.076 1.537c-1.336-.668-2.54-1.002-3.744-1.137c-.87-.135-1.74-.064-2.475 0h-.2c-.47 0-1.47.2-2.81.735c-.467.203-.735.336-.735.336s1.002-1.002 3.21-1.537l-.135-.135s-1.672-.064-3.477 1.27c0 0-1.805 3.144-1.805 7.02c0 0 1 1.74 3.743 1.806c0 0 .4-.533.805-1.002c-1.54-.468-2.14-1.404-2.14-1.404s.134.066.335.2h.06c.03 0 .044.015.06.03v.006c.016.016.03.03.06.03c.33.136.66.27.93.4a8.18 8.18 0 0 0 1.8.536c.93.135 1.996.2 3.21 0c.6-.135 1.2-.267 1.8-.535c.39-.2.87-.4 1.397-.737c0 0-.6.936-2.205 1.404c.33.466.795 1 .795 1c2.744-.06 3.81-1.8 3.87-1.726c0-3.87-1.815-7.02-1.815-7.02c-1.635-1.214-3.165-1.26-3.435-1.26l.056-.02zm.168 4.413c.703 0 1.27.6 1.27 1.335c0 .74-.57 1.34-1.27 1.34c-.7 0-1.27-.6-1.27-1.334c.002-.74.573-1.338 1.27-1.338zm-4.543 0c.7 0 1.266.6 1.266 1.335c0 .74-.57 1.34-1.27 1.34c-.7 0-1.27-.6-1.27-1.334c0-.74.57-1.338 1.27-1.338z"></path></svg>
                <small class="d-md-none ms-2">Discord</small>
              </a>
            </li>
          </ul>
          <form action="{{ url_for('webpages.search') }}" method="post" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" id="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      <div class="container-fluid">
        <div class="row">
          <nav id="sidebarMenu" class="col-md-2 col-lg-1 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
              <ul class="nav flex-column">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{{ url_for('webpages.dashboard') }}">
                    <span data-feather="home"></span>
                    Dashboard
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('staticpages.faq') }}">
                    <span data-feather="file"></span>
                    FAQ
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('webpages.items') }}">
                    <span data-feather="shopping-cart"></span>
                    Items
                  </a>
              </ul>
      
              <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Manufacturers</span>
              </h6>
              <ul class="nav flex-column mb-2">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('webpages.manufacturer_items', manufacturer='Rogue') }}">
                    <span data-feather="file-text"></span>
                    Rogue
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('webpages.manufacturer_items', manufacturer='Kabuki') }}">
                    <span data-feather="/items?brand=kabuki"></span>
                    Kabuki
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('webpages.manufacturer_items', manufacturer='ATX') }}">
                    <span data-feather="/items?brand=atx"></span>
                    ATX
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('webpages.manufacturer_items', manufacturer='Ironmaster') }}">
                    <span data-feather=/items?brand=ironmaster"></span>
                    Ironmaster
                  </a>
                </li>
              </ul>
            </div>
          </nav>

          
    {% endblock %} {% block content %}
    <div class="container">
      {# application content needs to be provided in the app_content block #} {%
      block app_content %}{% endblock %}
    </div>
    {% endblock %}

  <footer class="footer mt-auto py-3 bg-light">
    <div class="container">
      <span class="text-muted">Place sticky footer content here.</span>
    </div>
  </footer>
  
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/brand_items.html
{% extends "base.html" %} 
{% block app_content %}
<main class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
      <div class="lh-1">
        {% if title %}
          <h1 class="h6 mb-0 text-white lh-1">{{ title }}</h1>
          <small>Page {{ page_num }}</small>
        {% else %}
          <h1 class="h6 mb-0 text-white lh-1">Items</h1>
          <small>Page {{ page_num }}</small>
        {% endif %}
      </div>
    </div>
  
    <div class="my-3 p-3 bg-body rounded shadow-sm">
      {% for item in paginated_items.items %} 
      {% include '_item.html' %} 
      {% endfor %}
      <small class="d-block text-end mt-3">
        <a href="#">Suggest an item</a>
      </small>
    </div>

    {# Macro for creating navigation links #}
{% macro render_navigation(pagination, endpoint, title) %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if pagination.has_prev %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for(endpoint, page=pagination.prev().page, manufacturer=title) }}" tabindex="-1">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1">Previous</a>
    </li>
    {% endif %}
  {% for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li class="page-item"><a class="page-link" href="{{ url_for(endpoint, page=page, manufacturer=title) }}">{{ page }} </a></li>
      {% else %}
        <li class="page-item active"><a class="page-link" href="{{ url_for(endpoint, page=page, manufacturer=title) }}">{{ page }} </a></li>
      {% endif %}
    {% else %}
      <span class=ellipsis>…</span>
    {% endif %}
  {% endfor %}

    {% if pagination.has_next %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for(endpoint, page=pagination.next().page, manufacturer=title) }}" tabindex="-1">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endmacro %}

{{ render_navigation(paginated_items, 'webpages.manufacturer_items', title) }}

{% endblock %}

templates/dashboard.html
{% extends "base.html" %} 
{% block app_content %}
<main class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
      <div class="lh-1">
        <h1 class="h6 mb-0 text-white lh-1">Dashboard</h1>
        <small>Last refreshed on {{ date }}</small>
      </div>
    </div>
  
    <div class="my-3 p-3 bg-body rounded shadow-sm">
      <h6 class="border-bottom pb-2 mb-0" style="color:green">Currently in stock</h6>
      {% for item in items %} 
      {% include '_item.html' %} 
      {% endfor %}
      <small class="d-block text-end mt-3">
        <a href="/items">All items</a>
      </small>
    </div>
    
    <div class="my-3 p-3 bg-body rounded shadow-sm">
      <h6 class="border-bottom pb-2 mb-0" style="color:crimson">Recent updates </h6>
      {% for change in changes %} 
      {% include 'dashboard_change.html' %} 
      {% endfor %}
      <small class="d-block text-end mt-3">
        <a href="#">All updates</a>
      </small>
    </div>
  


{% endblock %}

templates/dashboard_change.html
<div class="d-flex text-muted pt-3">
  <p class="pb-3 mb-0 small lh-sm border-bottom">
    <strong class="d-block text-gray-dark">{{ change.item_name }}</strong>
    {% if change.restock %}
    <a>Restocked on {{ change.timestamp }}</a>
    {% else %}
    <a>Out of stock on {{ change.timestamp }}</a>
    {% endif %}
  </p>
</div>

templates/dashboard_item.html
<div class="d-flex text-muted pt-3">
    <p class="pb-3 mb-0 small lh-sm border-bottom">
      <strong class="d-block text-gray-dark">{{ item.name }}</strong>
      {% if item.price %} 
        <a style="color: green;"> ${{ item.price }} </a><br> 
      {% endif %}
      {% if item.config %}
        {% for configuration in item.config %}
          {{ configuration.config_name}}: 
          {% if configuration.stock %}
          <a style="color:darkgreen">In stock</a><br>
          {% else %}
          <a style="color: red;">Out of stock</a><br>
          {% endif %}
        {% endfor %} 
      {% endif %} 
    </p>
  </div>
   

templates/faq.html
{% extends "base.html" %} {% block app_content %}
<main class="container">
  <div
    class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm"
  >
    <div class="lh-1">
      <h1 class="h6 mb-0 text-white lh-1">FAQ</h1>
      <small>Frequently asked questions</small>
    </div>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">How can we help you?</h6>
    <div class="d-flex text-muted pt-3">
      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark">Why stockbot?</strong>
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
        veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
        occaecat cupidatat non proident, sunt in culpa qui officia deserunt
        mollit anim id est laborum."
      </p>
    </div>
    <div class="d-flex text-muted pt-3">
        <p class="pb-3 mb-0 small lh-sm border-bottom">
          <strong class="d-block text-gray-dark">How does it work?</strong>
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
          veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
          velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
          occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum."
        </p>
      </div>
      <div class="d-flex text-muted pt-3">
        <p class="pb-3 mb-0 small lh-sm border-bottom">
          <strong class="d-block text-gray-dark">Is it free?</strong>
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
          veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
          velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
          occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum."
        </p>
      </div>
    <small class="d-block text-end mt-3">
      <a href="#">Got a question?</a>
    </small>
  </div>

  {% endblock %}
</main>

templates/itemlist_item.html
<div class="d-flex text-muted pt-3">

    <p class="pb-3 mb-0 small lh-sm border-bottom">
        {% if item.stock %}
        <strong class="d-block text-gray-dark" style="color: green;">{{ item.name }}</strong>
        {% else %}
        <strong class="d-block text-gray-dark" style="color:crimson;">{{ item.name }}</strong>
        {% endif %}  
        {% if item.price %} ${{ item.price }} {% endif %}
    </p>
  </div>
  

templates/items.html
{% extends "base.html" %} 
{% block app_content %}
<main class="container">
    <div class="d-flex align-items-center p-3 my-3 text-white bg-dark rounded shadow-sm">
      <div class="lh-1">
        {% if title %}
          <h1 class="h6 mb-0 text-white lh-1">{{ title }}</h1>
          <small>Page {{ page_num }}</small>
        {% else %}
          <h1 class="h6 mb-0 text-white lh-1">Items</h1>
          <small>Page {{ page_num }}</small>
        {% endif %}
      </div>
    </div>
  
    <div class="my-3 p-3 bg-body rounded shadow-sm">
      <!-- <h6 class="border-bottom pb-2 mb-0">Page {{ page_num }}</h6> -->
      {% for item in paginated_items.items %} 
      {% include '_item.html' %} 
      {% endfor %}
      <small class="d-block text-end mt-3">
        <a href="#">Suggest an item</a>
      </small>
    </div>

    {# Macro for creating navigation links #}
{% macro render_navigation(pagination, endpoint) %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if pagination.has_prev %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for('webpages.items', page=pagination.prev().page) }}" tabindex="-1">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1">Previous</a>
    </li>
    {% endif %}
  {% for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li class="page-item"><a class="page-link" href="{{ url_for('webpages.items', page=page) }}">{{ page }} </a></li>
      {% else %}
        <li class="page-item active"><a class="page-link" href="{{ url_for('webpages.items', page=page) }}">{{ page }} </a></li>
      {% endif %}
    {% else %}
      <span class=ellipsis>…</span>
    {% endif %}
  {% endfor %}

    {% if pagination.has_next %}
    <li class="page-item">
      <a class="page-link" href="{{ url_for('webpages.items', page=pagination.next().page) }}" tabindex="-1">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" tabindex="-1">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endmacro %}

{{ render_navigation(paginated_items, 'webpages.items') }}


{% endblock %}